Character Input : Create a personal form 

In [1]:
name = str(input("The name is "))
age = int(input("The age is "))
gender = str(input("Gender: "))


The name is Additya
The age is 22
Gender: Male


Odd even check

In [21]:
num = int(input())

7


In [22]:
if num==0:
    print("{} is neither odd nor even" .format(num))
elif num%2==0:
    print("the number {}  is even" .format(num))    
else:
    print('the number {} is odd' .format(num))

the number 7 is odd


Divisibility Checker

In [23]:
num1 = int(input())
num2 = int(input())

2
3


In [24]:
num1/num2

0.6666666666666666

In [1]:
# Python program to demonstrate working 
# of map. 
  
# Return double of n 
def addition(n): 
    return n + n 
  
# We double all numbers using map() 
numbers = (1, 2, 3, 4) 
result = map(addition, numbers) 
print(list(result)) 

[2, 4, 6, 8]


List Less Than Ten

In [7]:
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

In [13]:
lis = [l<10 for l in a]
lis

[True, True, True, True, True, True, False, False, False, False, False]

In [19]:
my_list = [x for x in a if x<10]
my_list

[1, 1, 2, 3, 5, 8]

In [20]:
ll = []
for _ in a:
    if _<10:
        ll.append(_) 

In [21]:
ll

[1, 1, 2, 3, 5, 8]

In [24]:
x = range(2,11)
for _ in x:
    print(_)

2
3
4
5
6
7
8
9
10


Divisors

In [1]:
n = int(input())

30


In [5]:
for x in range(1, n+1):
    if n%x ==0:
        print(x)

1
2
3
5
6
10
15
30


List Overlap

In [6]:
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [9]:
c =  set(a+b)
c

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 21, 34, 55, 89}

Check Palindrome

In [9]:
a = str(input('check for palindrome   '))

check for palindrome   asdffdsa


In [10]:
if a==a[::-1]:
    print('The string is Palindrome')
else:
    print('The string is not Palindrome')

The string is Palindrome


List Comprehension

In [11]:
a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [17]:
x = [_ for _ in a] 
x

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Rock Paper Scissors

In [9]:
a = ('scissor')
b = ('rock')


if a==b:
    print('The game is a tie')
    
elif a== 'rock':
    if b=='paper':
        print('Player B is the winner')
    else:
        print('Player A is the winner')
elif a== 'paper':
    if b=='scissor':
        print('Player B is the winner')
    else:
        print('Player A is the winner')
elif a== 'scissor':
    if b=='rock':
        print('Player B is the winner')
    else:
        print('Player A is the winner')
else:
    print('You have done an invalid choice of input')
                
    


Player B is the winner


Generate a random number between 1 and 9 (including 1 and 9). Ask the user to guess the number, then tell them whether they guessed too low, too high, or exactly right. 

In [1]:
import numpy as np

In [41]:
a = np.random.randint(0,10)


In [44]:
num = int(input())

6


In [45]:
if a == num:
    print('Wow that was amazing. How did you guess that????')
elif a-num >= 4:
    print('The number is too far')
elif num-a<= -4:
    print('The number is too far p2')
elif a-num <=2 and a-num>0:
    print('You are close to the number')
elif num-a>=-2 and num-a<0:
    print('You are close to the number p2')
else:
    print('Wow that was bad')
    

Wow that was amazing. How did you guess that????


In [30]:
a

8

Take two lists, say for example these two:

	a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
	b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
and write a program that returns a list that contains only the elements that are common between the lists (without duplicates). Make sure your program works on two lists of different sizes

In [49]:
a = np.arange(1,160,4)
a

array([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
        53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101,
       105, 109, 113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153,
       157])

In [50]:
b = np.arange(1,150, 6)
b

array([  1,   7,  13,  19,  25,  31,  37,  43,  49,  55,  61,  67,  73,
        79,  85,  91,  97, 103, 109, 115, 121, 127, 133, 139, 145])

In [59]:
c = [x for x in a if x in b]
c

[1, 13, 25, 37, 49, 61, 73, 85, 97, 109, 121, 133, 145]

Ask the user for a number and determine whether the number is prime or not.

In [76]:
num = int(input())

20


In [77]:
if 0 not in [(num%_ )for _ in np.arange(2,num)]:
    print('{} is a prime number'.format(num))
else:
    print('{} is a composite number'.format(num))

20 is a composite number


In [91]:
a = [1,2,3,4,5]

In [92]:
lst = []
lst.append(a[0])
lst.append(a[::-1][0])
lst

[1, 5]

create 100x100 matrix from numbers 1 to 10000

In [94]:
np.arange(1,10001).reshape(100,100)

array([[    1,     2,     3, ...,    98,    99,   100],
       [  101,   102,   103, ...,   198,   199,   200],
       [  201,   202,   203, ...,   298,   299,   300],
       ...,
       [ 9701,  9702,  9703, ...,  9798,  9799,  9800],
       [ 9801,  9802,  9803, ...,  9898,  9899,  9900],
       [ 9901,  9902,  9903, ...,  9998,  9999, 10000]])

Get the longest word from a list of string words

In [99]:
words=["alpha","omega","up","down","over","under","purple","red","blue","green"]
sortedwords = sorted(words, key=len)
sortedwords[::-1][0]

'purple'